version: '3.8'

services:
  oracle:
    image: gvenzl/oracle-xe:latest
    container_name: oracle-xe
    environment:
      - ORACLE_PASSWORD=oracle
      - ORACLE_DATABASE=XE
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "system/oracle@//localhost:1521/XE", "AS", "SYSDBA"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: esg-energy-app
    depends_on:
      oracle:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle:1521:XE
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=oracle
    volumes:
      - ./src:/app/src
      - ./target:/app/target

volumes:
  oracle-data: